version: '3.8'

services:
  web:
    container_name: chessRush
    build:
      context: ./chessRush
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./chessRush/:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
