version: '3.3'

services:
  web:
    container_name: chessRush
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./chessRush/:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis-service-chess-rush
    ports:
      - "6379:6379"

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./chessRush/static:/static

    depends_on: 
      - web

 