# Generated by Django 4.1.3 on 2023-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField()),
                ('moves', models.TextField()),
                ('theme', models.TextField(default='')),
                ('url', models.URLField()),
                ('opening_fam', models.TextField()),
                ('opening_variation', models.TextField()),
            ],
        ),
    ]
