# Generated by Django 4.1.3 on 2023-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_automatefen'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatefen',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='automatefen',
            name='fen',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
